[UPDATE] 4.1.0
seontechnologies/seon-android-sdk-public pull request #6
Opened 2022-10-12 14:07 UTC by robertorsulics-seon

2022-10-12 14:19 UTC, istvanignacz-seon approved these changes

2022-10-13 07:01 UTC, istvanignacz-seon approved these changes

2022-10-13 07:29 UTC, materudasi-seon requested changes

2022-10-13 07:29 UTC, materudasi-seon commented on README.md
>  #### 4.0.0
Please add a new line above 4.0.0

2022-10-13 07:47 UTC, materudasi-seon approved these changes

2022-10-13 07:49 UTC, merged